name: rpassword rust tests

on: pull_request

jobs:
  rust-linux-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path Cargo.toml

  rust-windows-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path Cargo.toml
